#!/usr/bin/env python3
"""Phase 16Y / WAITCNT / STEP 2 -- pin the gfx1030 `s_waitcnt` encoding to
ASSEMBLER GROUND TRUTH before any Candidate F byte is decoded.

Why this exists: a prior phase asserted an encoding layout "recalled from
memory" and was wrong in three places.  Decoding Candidate F opcodes with a
bit-field guess is the same mistake.  Every field position reported here is
FITTED to bytes that ROCm 6.4's own offline assembler produced for
`--mcpu=gfx1030`, over an EXHAUSTIVE cross-product, and the fit is required to
be perfect and uniquely invertible.  A decoder that has not been pinned this
way is not a decoder.

Method
  1. Emit one `.s` containing every probe instruction back to back, assemble
     with `llvm-mc --triple=amdgcn-amd-amdhsa --mcpu=gfx1030` to an object, and
     read `.text` bytes out of the ELF IN PYTHON.
     `llvm-objcopy` is deliberately NOT used anywhere in this phase -- a prior
     phase's `objcopy --dump-section` without `-o` rewrote a frozen artifact in
     place.  No HIP, no ROCm *runtime*, no GPU, no device.
  2. Cross-product: vmcnt x lgkmcnt x expcnt over a value grid that includes
     every boundary (0, 1, powers of two, n-1, n) so a split or non-contiguous
     field cannot hide.
  3. FIT: recover, per operand, the SET OF WORD BITS that the operand drives,
     by differencing words against the all-max ("no wait") word.  Report the
     empirical positions, do not assume them.
  4. REQUIRE: (a) the fit predicts every probe word exactly; (b) the map
     operand-triple -> word is injective over the grid; (c) the recovered
     operands equal the typed operands for every probe.
  5. CROSS-CHECK against an independent surface: the project's own static
     disassembly census (`phase16x/audit/J3_STATIC_SCAN.json`
     `waitcnt_operands_histogram` / `waitcnt_opcode_histogram`) already pairs
     32-bit words with disassembler operand text for the 28 opcodes that occur
     in Candidate F.  Agreement between the assembler, my fitted decoder, and
     the disassembler on all of them is required.
"""
from __future__ import annotations

import itertools
import json
import os
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
ASM = os.path.join(HERE, "asm")
LLVM_MC = r"<ROCM_ROOT>\6.4\bin\llvm-mc.exe"
CLANG = r"<ROCM_ROOT>\6.4\bin\clang.exe"
ARCH = "gfx1030"

SCAN = os.path.join(ROOT, "phase16x", "audit", "J3_STATIC_SCAN.json")

# operand value grid -- boundaries, not a random sample
V = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 16, 17, 31, 32, 33, 40, 47, 48,
     62, 63]
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 16, 17, 31, 32, 33, 40, 47, 48,
     62, 63]
E = [0, 1, 2, 3, 4, 5, 6, 7]
D = [0x000, 0x001, 0x00f, 0x0f0, 0x0ff, 0x100, 0x1e7, 0x800, 0xfff]


def probe_lines():
    """Every single-field and every cross-product waitcnt word we can name."""
    out = []
    # one field varied, the others at their "don't wait" maximum
    for v in V:
        out.append(("vm%02d" % v, "s_waitcnt vmcnt(%d)" % v,
                    {"vmcnt": v, "lgkmcnt": 63, "expcnt": 7}))
    for l in L:
        out.append(("lg%02d" % l, "s_waitcnt lgkmcnt(%d)" % l,
                    {"vmcnt": 63, "lgkmcnt": l, "expcnt": 7}))
    for e in E:
        out.append(("ex%d" % e, "s_waitcnt expcnt(%d)" % e,
                    {"vmcnt": 63, "lgkmcnt": 63, "expcnt": e}))
    # full cross-product over a sub-grid small enough to assemble at once
    for v, l, e in itertools.product([0, 1, 2, 3, 7, 8, 16, 17, 31, 32, 40,
                                      62, 63],
                                     [0, 1, 2, 3, 7, 8, 16, 17, 31, 32, 40,
                                      62, 63],
                                     E):
        out.append(("x_%02d_%02d_%d" % (v, l, e),
                    "s_waitcnt vmcnt(%d) lgkmcnt(%d) expcnt(%d)" % (v, l, e),
                    {"vmcnt": v, "lgkmcnt": l, "expcnt": e}))
    for d in D:
        out.append(("dep_%03x" % d, "s_waitcnt_depctr 0x%03x" % d,
                    {"depctr": d}))
    return out


def build_and_assemble(lines):
    os.makedirs(ASM, exist_ok=True)
    src = os.path.join(ASM, "all_probes.s")
    obj = os.path.join(ASM, "all_probes.o")
    with open(src, "w", newline="\n") as f:
        f.write("// generated by p16y_probe_build.py -- do not hand edit\n")
        f.write(".text\n")
        for _tag, text, _o in lines:
            f.write("%s\n" % text)
    cmd = [LLVM_MC, "--triple=amdgcn-amd-amdhsa", "--mcpu=%s" % ARCH,
           "--filetype=obj", "-o", obj, src]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit("llvm-mc failed:\n%s\n%s" % (r.stdout, r.stderr))
    # also produce a clang-assembled copy of a sub-sample, so the pin does not
    # rest on one front end.
    return obj


def text_section(obj, want=".text"):
    with open(obj, "rb") as f:
        data = f.read()
    assert data[:4] == b"\x7fELF", obj
    shentsize = struct.unpack_from("<H", data, 0x3A)[0]
    shoff = struct.unpack_from("<Q", data, 0x28)[0]
    shnum = struct.unpack_from("<H", data, 0x3C)[0]
    shstrndx = struct.unpack_from("<H", data, 0x3E)[0]

    def sec(i):
        o = shoff + i * shentsize
        name, typ, flags, addr, off, size = struct.unpack_from(
            "<IIQQQQ", data, o)
        return {"name": name, "addr": addr, "off": off, "size": size}

    st = sec(shstrndx)

    def nm(s):
        o = st["off"] + s
        return data[o:data.index(b"\0", o)].decode()

    for i in range(shnum):
        s = sec(i)
        if nm(s["name"]) == want:
            return data[s["off"]:s["off"] + s["size"]], s["addr"]
    raise SystemExit("no %s section in %s" % (want, obj))


def fit_fields(cases):
    """Recover, per operand name, the exact set of word bits it drives.

    `cases` is [(operands_dict, word)].  A bit belongs to operand `k` iff,
    holding every other operand at the reference value, flipping `k` flips
    that bit.  Bits driven by more than one operand are reported as COINCIDENT
    and excluded, because a decoder cannot invert them.
    """
    ref = None
    for ops, _w in cases:
        if "vmcnt" in ops and ops.get("vmcnt") == 63 and \
                ops.get("lgkmcnt") == 63 and ops.get("expcnt") == 7:
            ref = (ops, _w)
            break
    if ref is None:
        raise SystemExit("no reference (all-don't-wait) probe in the grid")
    rops, rword = ref
    names = [n for n in ("vmcnt", "lgkmcnt", "expcnt", "depctr")
             if any(n in ops for ops, _ in cases)]
    driven = {}
    for name in names:
        per_bit = {}
        for ops, w in cases:
            if name not in ops or name not in rops:
                continue
            if any(ops.get(o) != rops.get(o) for o in rops
                   if o != name):
                continue           # only single-field deviations
            diff = w ^ rword
            val = ops[name]
            for b in range(32):
                if (diff >> b) & 1:
                    per_bit.setdefault(b, set()).add(val)
        # keep bits that this operand demonstrably drives
        driven[name] = sorted(per_bit)
    # exclusivity
    overlap = {}
    owner = {}
    for name, bits in driven.items():
        for b in bits:
            if b in owner:
                overlap.setdefault(b, [owner[b]]).append(name)
            owner[b] = name
    return driven, overlap, ref


def make_decoder(driven):
    """Build bit masks from the empirically recovered positions."""
    masks = {}
    for name, bits in driven.items():
        m = 0
        for b in bits:
            m |= (1 << b)
        masks[name] = m
    return masks


def dec(masks, name, w):
    m = masks[name]
    lo = (m & -m).bit_length() - 1
    return (w & m) >> lo


def main():
    for p in (LLVM_MC, CLANG):
        if not os.path.exists(p):
            raise SystemExit("MISSING tool: %s" % p)
    lines = probe_lines()
    print("probes: %d" % len(lines))
    obj = build_and_assemble(lines)
    tb, taddr = text_section(obj, ".text")
    print(".text @0x%X, %d bytes (expect %d)" % (taddr, len(tb),
                                                  4 * len(lines)))
    if len(tb) != 4 * len(lines):
        raise SystemExit("REFUSING: .text is not one 4-byte word per probe "
                         "-- the alignment assumption behind this whole "
                         "comparison is wrong")
    cases = []
    for (tag, text, ops), off in zip(lines, range(0, len(tb), 4)):
        w = struct.unpack_from("<I", tb, off)[0]
        cases.append((tag, ops, w))

    wc = [(ops, w) for _t, ops, w in cases if "vmcnt" in ops]
    dc = [(ops, w) for _t, ops, w in cases if "depctr" in ops]
    driven, overlap, ref = fit_fields(wc)
    driven_d, overlap_d, _ = fit_fields(dc)
    driven.update(driven_d)
    print("\nEMPIRICAL FIELD POSITIONS (bits recovered by differencing, not "
          "assumed):")
    for name in ("vmcnt", "lgkmcnt", "expcnt", "depctr"):
        if name in driven:
            print("  %-8s bits %s" % (name, driven[name]))
    if overlap:
        print("  COINCIDENT bits (driven by >1 operand): %s" % overlap)
    masks = make_decoder(driven)
    print("  masks: %s" % {k: "0x%08X" % v for k, v in masks.items()})

    # ---- requirement 3a/3b/3c ------------------------------------------
    bad_pred = []
    seen = {}
    for tag, ops, w in cases:
        rebuilt = 0
        for name, m in masks.items():
            if name not in ops:
                continue
            lo = (m & -m).bit_length() - 1
            rebuilt |= (ops[name] << lo) & m
        # opcode/prefix bits are the constant remainder
        prefix = w & ~sum(masks.values())
        if (rebuilt | prefix) != w:
            bad_pred.append((tag, "%08X" % w, "%08X" % (rebuilt | prefix)))
        got = {n: dec(masks, n, w) for n in ops if n in masks}
        if got != {k: v for k, v in ops.items() if k in masks}:
            bad_pred.append((tag, "roundtrip %s != %s" % (got, ops), ""))
        key = tuple(sorted(ops.items()))
        if key in seen and seen[key] != w:
            bad_pred.append((tag, "non-deterministic", hex(seen[key])))
        seen[key] = w
        if w in [v for _t, _o, v in cases if _t != tag] and \
                any(v == w for _t, _o, v in cases if _t != tag):
            clash = [t for t, o, v in cases if v == w and t != tag]
            if any(o != ops for t, o, v in cases if t in clash):
                bad_pred.append((tag, "word collision with %s" % clash, ""))
    print("\nfit failures: %d / %d probes" % (len(bad_pred), len(cases)))
    for t in bad_pred[:15]:
        print("   ", t)

    # ---- requirement 5: independent cross-check vs the project's own
    #      disassembly census of Candidate F
    scan = json.load(open(SCAN, encoding="utf-8"))
    op_hist = scan["waitcnt_opcode_histogram"]
    operand_hist = scan["waitcnt_operands_histogram"]
    # map operand text -> expected triple
    def parse_operand(s):
        if s.startswith("null"):
            return None
        if s == "0xfff":
            return {"depctr": 0xfff}
        d = {"vmcnt": 63, "lgkmcnt": 63, "expcnt": 7}
        ok = True
        for part in s.split():
            k, _, rest = part.partition("(")
            n = int(rest.rstrip(")"))
            if k in d:
                d[k] = n
            else:
                ok = False
        return d if ok else None
    agree, disagree, skipped = [], [], []
    for wordhex, count in op_hist.items():
        w = int(wordhex, 16)
        # the census stores the word as printed (big-endian display of the
        # 32-bit instruction), same form llvm-objdump uses
        # find the disassembler's operand text: the histogram key pairing is
        # lost, so match by trying every operand string and requiring exactly
        # one to produce this word.
        cands = []
        for otext in operand_hist:
            ops = parse_operand(otext)
            if ops is None:
                continue
            rebuilt = w & ~sum(masks.values())
            for name, m in masks.items():
                lo = (m & -m).bit_length() - 1
                rebuilt |= (ops.get(name, dec(masks, name, w)) << lo) & m
            if rebuilt == w:
                cands.append(otext)
        if not cands:
            skipped.append((wordhex, count))
            continue
        agree.append((wordhex, count, cands))
        if len(cands) > 1:
            disagree.append((wordhex, cands))
    print("\nCandidate F opcode census: %d distinct words, %d matched by the "
          "fitted decoder, %d unmatched, %d ambiguous"
          % (len(op_hist), len(agree) - len(disagree), len(skipped),
             len(disagree)))
    for s in skipped:
        print("    UNMATCHED %s x%d" % (s[0], s[1]))
    for d in disagree:
        print("    AMBIGUOUS   %s -> %s" % (d[0], d[1]))

    out = {
        "schema": "phase16y-waitcnt-probe/1",
        "assembler": LLVM_MC, "arch": ARCH,
        "n_probes": len(cases),
        "objdump_words_saved": len(cases),
        "empirical_field_bits": {k: v for k, v in driven.items()},
        "empirical_field_masks": {k: "0x%08X" % v for k, v in masks.items()},
        "coincident_bits": {str(k): v for k, v in (overlap or {}).items()},
        "fit_failures": [list(x) for x in bad_pred],
        "fit_clean": not bad_pred,
        "candidate_f_census_words": len(op_hist),
        "census_unmatched": [[a, b] for a, b in skipped],
        "census_ambiguous": disagree,
        "opcodes": [{"tag": t, "operands": o, "word": "0x%08X" % w}
                    for t, o, w in cases],
    }
    with open(os.path.join(HERE, "probe_results.json"), "w",
              encoding="utf-8") as f:
        json.dump(out, f, indent=1)
    print("\nwrote probe_results.json")
    return 0 if not bad_pred else 1


if __name__ == "__main__":
    sys.exit(main())
