// GENERATED by p16aw/raw_dump/p16aw_author_argspec.py -- DO NOT EDIT.
//
// The argument-spec table of RAW_DUMP_ARGSPEC_16AW.json, in a form the
// repaired capture layer compiles against. Both are written from ONE table
// object in one run, and the JSON's digest is carried below, so the table the
// layer compiles and the table the verifier reads cannot drift apart.
//
// Derived from the ORIGINAL module's code object metadata
// (phase9_original_kernel_metadata.json), cross-checked against the Itanium
// mangled symbol and the 16AO first-frame closure. See the JSON for the
// per-field evidence sources.
#pragma once

#include <cstddef>

namespace rd16aw {

constexpr const char* kArgspecJsonSha256 = "56c17e4f1e2f7395629aba09c909732cfc96ae103f5b29a641646c52ddec491a";

enum ArgKind { KIND_POINTER = 0, KIND_SCALAR = 1, KIND_BY_VALUE_STRUCT = 2,
               KIND_OTHER_EXPLICIT = 3 };

struct ArgSpec {
    unsigned    host_arg_index;
    unsigned    bytes;                 // explicit_byte_size
    unsigned    kind;                  // ArgKind
    unsigned    alignment;
    unsigned    kernarg_offset;        // canonical explicit-kernarg offset
    const char* value_kind;            // the code object's own spelling
    const char* type_name;
};

struct HiddenArg {
    const char* value_kind;
    unsigned    kernarg_offset;
    unsigned    bytes;
};

struct KernelSpec {
    const char*          identity;
    unsigned             kernarg_segment_size;
    unsigned             kernarg_segment_align;
    unsigned             n_explicit;
    const ArgSpec*       explicit_args;
    unsigned             n_hidden;
    const HiddenArg*     hidden_args;
};

static const ArgSpec k10kflagsetPjj_args[] = {
    {0u, 8u, 0u, 8u, 0u, "global_buffer", "unsigned int*"},
    {1u, 4u, 1u, 8u, 8u, "by_value", "unsigned int"},
};
static const HiddenArg k10kflagsetPjj_hidden[] = {
};

static const ArgSpec k11kconvres211Conv2Params_args[] = {
    {0u, 64u, 2u, 8u, 0u, "by_value", "Conv2Params"},
};
static const HiddenArg k11kconvres211Conv2Params_hidden[] = {
    {"hidden_block_count_x", 64u, 4u},
    {"hidden_block_count_y", 68u, 4u},
    {"hidden_block_count_z", 72u, 4u},
    {"hidden_group_size_x", 76u, 2u},
    {"hidden_group_size_y", 78u, 2u},
    {"hidden_group_size_z", 80u, 2u},
    {"hidden_remainder_x", 82u, 2u},
    {"hidden_remainder_y", 84u, 2u},
    {"hidden_remainder_z", 86u, 2u},
    {"hidden_global_offset_x", 104u, 8u},
    {"hidden_global_offset_y", 112u, 8u},
    {"hidden_global_offset_z", 120u, 8u},
    {"hidden_grid_dims", 128u, 2u},
};

static const ArgSpec k11kflagwaitPjjj_args[] = {
    {0u, 8u, 0u, 8u, 0u, "global_buffer", "unsigned int*"},
    {1u, 4u, 1u, 8u, 8u, "by_value", "unsigned int"},
    {2u, 4u, 1u, 4u, 12u, "by_value", "unsigned int"},
};
static const HiddenArg k11kflagwaitPjjj_hidden[] = {
};

static const ArgSpec k11kqkvattn210AttnParams_args[] = {
    {0u, 40u, 2u, 8u, 0u, "by_value", "AttnParams"},
};
static const HiddenArg k11kqkvattn210AttnParams_hidden[] = {
    {"hidden_block_count_x", 40u, 4u},
    {"hidden_block_count_y", 44u, 4u},
    {"hidden_block_count_z", 48u, 4u},
    {"hidden_group_size_x", 52u, 2u},
    {"hidden_group_size_y", 54u, 2u},
    {"hidden_group_size_z", 56u, 2u},
    {"hidden_remainder_x", 58u, 2u},
    {"hidden_remainder_y", 60u, 2u},
    {"hidden_remainder_z", 62u, 2u},
    {"hidden_global_offset_x", 80u, 8u},
    {"hidden_global_offset_y", 88u, 8u},
    {"hidden_global_offset_z", 96u, 8u},
    {"hidden_grid_dims", 104u, 2u},
};

static const ArgSpec k12kattention212AttnParams1d_args[] = {
    {0u, 40u, 2u, 8u, 0u, "by_value", "AttnParams1d"},
};
static const HiddenArg k12kattention212AttnParams1d_hidden[] = {
    {"hidden_block_count_x", 40u, 4u},
    {"hidden_block_count_y", 44u, 4u},
    {"hidden_block_count_z", 48u, 4u},
    {"hidden_group_size_x", 52u, 2u},
    {"hidden_group_size_y", 54u, 2u},
    {"hidden_group_size_z", 56u, 2u},
    {"hidden_remainder_x", 58u, 2u},
    {"hidden_remainder_y", 60u, 2u},
    {"hidden_remainder_z", 62u, 2u},
    {"hidden_global_offset_x", 80u, 8u},
    {"hidden_global_offset_y", 88u, 8u},
    {"hidden_global_offset_z", 96u, 8u},
    {"hidden_grid_dims", 104u, 2u},
};

static const ArgSpec k12kfinalhead10HeadParams_args[] = {
    {0u, 24u, 2u, 8u, 0u, "by_value", "HeadParams"},
};
static const HiddenArg k12kfinalhead10HeadParams_hidden[] = {
    {"hidden_block_count_x", 24u, 4u},
    {"hidden_block_count_y", 28u, 4u},
    {"hidden_block_count_z", 32u, 4u},
    {"hidden_group_size_x", 36u, 2u},
    {"hidden_group_size_y", 38u, 2u},
    {"hidden_group_size_z", 40u, 2u},
    {"hidden_remainder_x", 42u, 2u},
    {"hidden_remainder_y", 44u, 2u},
    {"hidden_remainder_z", 46u, 2u},
    {"hidden_global_offset_x", 64u, 8u},
    {"hidden_global_offset_y", 72u, 8u},
    {"hidden_global_offset_z", 80u, 8u},
    {"hidden_grid_dims", 88u, 2u},
};

static const ArgSpec k14kdecupsample11DecUpParams_args[] = {
    {0u, 40u, 2u, 8u, 0u, "by_value", "DecUpParams"},
};
static const HiddenArg k14kdecupsample11DecUpParams_hidden[] = {
    {"hidden_block_count_x", 40u, 4u},
    {"hidden_block_count_y", 44u, 4u},
    {"hidden_block_count_z", 48u, 4u},
    {"hidden_group_size_x", 52u, 2u},
    {"hidden_group_size_y", 54u, 2u},
    {"hidden_group_size_z", 56u, 2u},
    {"hidden_remainder_x", 58u, 2u},
    {"hidden_remainder_y", 60u, 2u},
    {"hidden_remainder_z", 62u, 2u},
    {"hidden_global_offset_x", 80u, 8u},
    {"hidden_global_offset_y", 88u, 8u},
    {"hidden_global_offset_z", 96u, 8u},
    {"hidden_grid_dims", 104u, 2u},
};

static const ArgSpec k16kconvresviews12ConvPlParams_args[] = {
    {0u, 72u, 2u, 8u, 0u, "by_value", "ConvPlParams"},
};
static const HiddenArg k16kconvresviews12ConvPlParams_hidden[] = {
    {"hidden_block_count_x", 72u, 4u},
    {"hidden_block_count_y", 76u, 4u},
    {"hidden_block_count_z", 80u, 4u},
    {"hidden_group_size_x", 84u, 2u},
    {"hidden_group_size_y", 86u, 2u},
    {"hidden_group_size_z", 88u, 2u},
    {"hidden_remainder_x", 90u, 2u},
    {"hidden_remainder_y", 92u, 2u},
    {"hidden_remainder_z", 94u, 2u},
    {"hidden_global_offset_x", 112u, 8u},
    {"hidden_global_offset_y", 120u, 8u},
    {"hidden_global_offset_z", 128u, 8u},
    {"hidden_grid_dims", 136u, 2u},
};

static const ArgSpec k6kmean10MeanParams_args[] = {
    {0u, 32u, 2u, 8u, 0u, "by_value", "MeanParams"},
};
static const HiddenArg k6kmean10MeanParams_hidden[] = {
    {"hidden_block_count_x", 32u, 4u},
    {"hidden_block_count_y", 36u, 4u},
    {"hidden_block_count_z", 40u, 4u},
    {"hidden_group_size_x", 44u, 2u},
    {"hidden_group_size_y", 46u, 2u},
    {"hidden_group_size_z", 48u, 2u},
    {"hidden_remainder_x", 50u, 2u},
    {"hidden_remainder_y", 52u, 2u},
    {"hidden_remainder_z", 54u, 2u},
    {"hidden_global_offset_x", 72u, 8u},
    {"hidden_global_offset_y", 80u, 8u},
    {"hidden_global_offset_z", 88u, 8u},
    {"hidden_grid_dims", 96u, 2u},
};

static const ArgSpec k6kqkv29QkvParams_args[] = {
    {0u, 40u, 2u, 8u, 0u, "by_value", "QkvParams"},
};
static const HiddenArg k6kqkv29QkvParams_hidden[] = {
    {"hidden_block_count_x", 40u, 4u},
    {"hidden_block_count_y", 44u, 4u},
    {"hidden_block_count_z", 48u, 4u},
    {"hidden_group_size_x", 52u, 2u},
    {"hidden_group_size_y", 54u, 2u},
    {"hidden_group_size_z", 56u, 2u},
    {"hidden_remainder_x", 58u, 2u},
    {"hidden_remainder_y", 60u, 2u},
    {"hidden_remainder_z", 62u, 2u},
    {"hidden_global_offset_x", 80u, 8u},
    {"hidden_global_offset_y", 88u, 8u},
    {"hidden_global_offset_z", 96u, 8u},
    {"hidden_grid_dims", 104u, 2u},
};

static const ArgSpec k7kffwd211Ffwd2Params_args[] = {
    {0u, 48u, 2u, 8u, 0u, "by_value", "Ffwd2Params"},
};
static const HiddenArg k7kffwd211Ffwd2Params_hidden[] = {
    {"hidden_block_count_x", 48u, 4u},
    {"hidden_block_count_y", 52u, 4u},
    {"hidden_block_count_z", 56u, 4u},
    {"hidden_group_size_x", 60u, 2u},
    {"hidden_group_size_y", 62u, 2u},
    {"hidden_group_size_z", 64u, 2u},
    {"hidden_remainder_x", 66u, 2u},
    {"hidden_remainder_y", 68u, 2u},
    {"hidden_remainder_z", 70u, 2u},
    {"hidden_global_offset_x", 88u, 8u},
    {"hidden_global_offset_y", 96u, 8u},
    {"hidden_global_offset_z", 104u, 8u},
    {"hidden_grid_dims", 112u, 2u},
};

static const ArgSpec k8kexport12ExportParams_args[] = {
    {0u, 64u, 2u, 8u, 0u, "by_value", "ExportParams"},
};
static const HiddenArg k8kexport12ExportParams_hidden[] = {
    {"hidden_block_count_x", 64u, 4u},
    {"hidden_block_count_y", 68u, 4u},
    {"hidden_block_count_z", 72u, 4u},
    {"hidden_group_size_x", 76u, 2u},
    {"hidden_group_size_y", 78u, 2u},
    {"hidden_group_size_z", 80u, 2u},
    {"hidden_remainder_x", 82u, 2u},
    {"hidden_remainder_y", 84u, 2u},
    {"hidden_remainder_z", 86u, 2u},
    {"hidden_global_offset_x", 104u, 8u},
    {"hidden_global_offset_y", 112u, 8u},
    {"hidden_global_offset_z", 120u, 8u},
    {"hidden_grid_dims", 128u, 2u},
};

static const ArgSpec k8kimport12ImportParams_args[] = {
    {0u, 48u, 2u, 8u, 0u, "by_value", "ImportParams"},
};
static const HiddenArg k8kimport12ImportParams_hidden[] = {
    {"hidden_block_count_x", 48u, 4u},
    {"hidden_block_count_y", 52u, 4u},
    {"hidden_block_count_z", 56u, 4u},
    {"hidden_group_size_x", 60u, 2u},
    {"hidden_group_size_y", 62u, 2u},
    {"hidden_group_size_z", 64u, 2u},
    {"hidden_remainder_x", 66u, 2u},
    {"hidden_remainder_y", 68u, 2u},
    {"hidden_remainder_z", 70u, 2u},
    {"hidden_global_offset_x", 88u, 8u},
    {"hidden_global_offset_y", 96u, 8u},
    {"hidden_global_offset_z", 104u, 8u},
    {"hidden_grid_dims", 112u, 2u},
};

static const ArgSpec k8krepack12RepackParams_args[] = {
    {0u, 32u, 2u, 8u, 0u, "by_value", "RepackParams"},
};
static const HiddenArg k8krepack12RepackParams_hidden[] = {
    {"hidden_block_count_x", 32u, 4u},
    {"hidden_block_count_y", 36u, 4u},
    {"hidden_block_count_z", 40u, 4u},
    {"hidden_group_size_x", 44u, 2u},
    {"hidden_group_size_y", 46u, 2u},
    {"hidden_group_size_z", 48u, 2u},
    {"hidden_remainder_x", 50u, 2u},
    {"hidden_remainder_y", 52u, 2u},
    {"hidden_remainder_z", 54u, 2u},
    {"hidden_global_offset_x", 72u, 8u},
    {"hidden_global_offset_y", 80u, 8u},
    {"hidden_global_offset_z", 88u, 8u},
    {"hidden_grid_dims", 96u, 2u},
};

static const ArgSpec k9kexpand212ExpandParams_args[] = {
    {0u, 24u, 2u, 8u, 0u, "by_value", "ExpandParams"},
};
static const HiddenArg k9kexpand212ExpandParams_hidden[] = {
    {"hidden_block_count_x", 24u, 4u},
    {"hidden_block_count_y", 28u, 4u},
    {"hidden_block_count_z", 32u, 4u},
    {"hidden_group_size_x", 36u, 2u},
    {"hidden_group_size_y", 38u, 2u},
    {"hidden_group_size_z", 40u, 2u},
    {"hidden_remainder_x", 42u, 2u},
    {"hidden_remainder_y", 44u, 2u},
    {"hidden_remainder_z", 46u, 2u},
    {"hidden_global_offset_x", 64u, 8u},
    {"hidden_global_offset_y", 72u, 8u},
    {"hidden_global_offset_z", 80u, 8u},
    {"hidden_grid_dims", 88u, 2u},
};

static const KernelSpec kKernelSpecs[] = {
    {"_Z10k_flag_setPjj", 12u, 8u, 2u, k10kflagsetPjj_args, 0u, k10kflagsetPjj_hidden},
    {"_Z11k_conv_res211Conv2Params", 320u, 8u, 1u, k11kconvres211Conv2Params_args, 13u, k11kconvres211Conv2Params_hidden},
    {"_Z11k_flag_waitPjjj", 16u, 8u, 3u, k11kflagwaitPjjj_args, 0u, k11kflagwaitPjjj_hidden},
    {"_Z11k_qkv_attn210AttnParams", 296u, 8u, 1u, k11kqkvattn210AttnParams_args, 13u, k11kqkvattn210AttnParams_hidden},
    {"_Z12k_attention212AttnParams1d", 296u, 8u, 1u, k12kattention212AttnParams1d_args, 13u, k12kattention212AttnParams1d_hidden},
    {"_Z12k_final_head10HeadParams", 280u, 8u, 1u, k12kfinalhead10HeadParams_args, 13u, k12kfinalhead10HeadParams_hidden},
    {"_Z14k_dec_upsample11DecUpParams", 296u, 8u, 1u, k14kdecupsample11DecUpParams_args, 13u, k14kdecupsample11DecUpParams_hidden},
    {"_Z16k_conv_res_views12ConvPlParams", 328u, 8u, 1u, k16kconvresviews12ConvPlParams_args, 13u, k16kconvresviews12ConvPlParams_hidden},
    {"_Z6k_mean10MeanParams", 288u, 8u, 1u, k6kmean10MeanParams_args, 13u, k6kmean10MeanParams_hidden},
    {"_Z6k_qkv29QkvParams", 296u, 8u, 1u, k6kqkv29QkvParams_args, 13u, k6kqkv29QkvParams_hidden},
    {"_Z7k_ffwd211Ffwd2Params", 304u, 8u, 1u, k7kffwd211Ffwd2Params_args, 13u, k7kffwd211Ffwd2Params_hidden},
    {"_Z8k_export12ExportParams", 320u, 8u, 1u, k8kexport12ExportParams_args, 13u, k8kexport12ExportParams_hidden},
    {"_Z8k_import12ImportParams", 304u, 8u, 1u, k8kimport12ImportParams_args, 13u, k8kimport12ImportParams_hidden},
    {"_Z8k_repack12RepackParams", 288u, 8u, 1u, k8krepack12RepackParams_args, 13u, k8krepack12RepackParams_hidden},
    {"_Z9k_expand212ExpandParams", 280u, 8u, 1u, k9kexpand212ExpandParams_args, 13u, k9kexpand212ExpandParams_hidden},
};

constexpr std::size_t kNumKernelSpecs =
    sizeof(kKernelSpecs) / sizeof(kKernelSpecs[0]);

inline const KernelSpec* spec_lookup(const char* identity)
{
    if (identity == nullptr) { return nullptr; }
    for (std::size_t i = 0; i < kNumKernelSpecs; ++i) {
        const char* a = kKernelSpecs[i].identity;
        const char* b = identity;
        std::size_t k = 0;
        while (a[k] != '\0' && a[k] == b[k]) { ++k; }
        if (a[k] == '\0' && b[k] == '\0') { return &kKernelSpecs[i]; }
    }
    return nullptr;
}

// Hard cap on one captured argument. The largest explicit argument in the
// table is 72 B; the cap stops a corrupted table entry from turning the
// capture into an unbounded reader.
constexpr unsigned kMaxArgBytes = 4096u;

}  // namespace rd16aw
