#!/usr/bin/env python3
"""Phase 16AT RAW_DUMP -- generate the five capture mutants.

Each mutant is a full copy of p16at/raw_dump/src/raw_dump_recorder.cpp with
exactly ONE of the four injection macros changed, placed at
_work/mutants/<arm>/raw_dump_recorder.cpp.

WHY A COPY AND NOT AN -I FLAG
  raw_dump_recorder.cpp includes "raw_dump_injection_points.h" with quotes, and
  a quoted include is resolved against the INCLUDING FILE'S OWN DIRECTORY first.
  Adding -I<mutant dir> would therefore change nothing: the parent header beside
  the source would win and the mutant would compile as the parent -- a silent
  no-op mutator reporting the inverse fault. So the mutant is generated as a
  self-contained source with the macro definitions inlined.

Every mutant records:
  * the parent sha256 and the mutant sha256
  * the exact single line that changed, before and after
  * a measured assertion that the two differ in EXACTLY one line

Usage:
  python p16at_emit_mutants.py
"""

import hashlib
import json
import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
RAW_DUMP = os.path.dirname(HERE)
WORK = os.path.join(RAW_DUMP, "_work")
MUT_DIR = os.path.join(WORK, "mutants")
PARENT = os.path.join(HERE, "raw_dump_recorder.cpp")
INJECT_HDR = "raw_dump_injection_points.h"

# arm -> (macro name, parent body, mutant body, what it models)
MUTANTS = {
    "shift": (
        "RAWD_BLOB_POINTER", "(p)",
        "((const unsigned char*)(p) + 1)",
        "one-byte shift of the blob: the capture reads from blob+1"),
    "truncate": (
        "RAWD_BLOB_LENGTH", "(n)",
        "((std::size_t)(n) - 1)",
        "truncation: one byte short of the declared by-value size"),
    "declared_size": (
        "RAWD_BLOB_LENGTH", "(n)",
        "((std::size_t)(n) + 8)",
        "wrong blob size declared: the record claims 8 bytes more than the "
        "code object declares"),
    "ordinal": (
        "RAWD_LAUNCH_ORDINAL", "(n)",
        "((unsigned)(n) + 7919u)",
        "wrong launch ordinal"),
    "identity": (
        "RAWD_KERNEL_IDENTITY", "(s)",
        '("_Z9k_expand212ExpandParams")',
        "wrong kernel identity: the record names a different one of the 15"),
}

INLINE_BLOCK = """// ---- 16AT mutation: ONE injection macro, injected here ----------------
// Generated by p16at_emit_mutants.py from raw_dump_injection_points.h.
// Parent line : {pline}
// Mutant line : {mline}
// Arm         : {arm} -- {what}
#ifndef RAWD_BLOB_POINTER
#define RAWD_BLOB_POINTER(p) (p)
#endif
#ifndef RAWD_BLOB_LENGTH
#define RAWD_BLOB_LENGTH(n) (n)
#endif
#ifndef RAWD_LAUNCH_ORDINAL
#define RAWD_LAUNCH_ORDINAL(n) (n)
#endif
#ifndef RAWD_KERNEL_IDENTITY
#define RAWD_KERNEL_IDENTITY(s) (s)
#endif
#undef {macro}
#define {macro}({arg}) {body}
// -----------------------------------------------------------------------
"""


def sha(b):
    return hashlib.sha256(b).hexdigest()


def main():
    with open(PARENT, "rb") as f:
        parent = f.read()
    text = parent.decode("utf-8")
    with open(os.path.join(HERE, INJECT_HDR), "rb") as f:
        hdr_text = f.read().decode("utf-8")
    inc_line = '#include "%s"' % INJECT_HDR
    if text.count(inc_line) != 1:
        raise SystemExit("parent does not include the injection header once "
                         "(found %d)" % text.count(inc_line))

    os.makedirs(MUT_DIR, exist_ok=True)
    out = {
        "schema": "p16at/raw-dump-mutants/1",
        "phase": "16AT",
        "host_only": True,
        "gpu_execution_performed": False,
        "parent": os.path.relpath(PARENT, RAW_DUMP).replace("\\", "/"),
        "parent_sha256": sha(parent),
        "parent_bytes": len(parent),
        "why_a_copy_and_not_an_include_path": (
            "a quoted include resolves against the including file's own "
            "directory first, so -I<mutant dir> would be shadowed by the "
            "parent header and the mutant would compile as the parent"),
        "mutants": {},
    }
    for arm, (macro, pbody, mbody, what) in MUTANTS.items():
        # locate the actual parent line for this macro, in the header where it
        # is defined (the recorder .cpp only includes it)
        arg = {"RAWD_BLOB_POINTER": "p", "RAWD_BLOB_LENGTH": "n",
               "RAWD_LAUNCH_ORDINAL": "n", "RAWD_KERNEL_IDENTITY": "s"}[macro]
        pline = "#define %s(%s) %s" % (macro, arg, pbody)
        hits = [i for i, l in enumerate(hdr_text.split("\n")) if l == pline]
        if len(hits) != 1:
            raise SystemExit("parent macro line %r occurs %d times in %s, "
                             "expected 1" % (pline, len(hits), INJECT_HDR))
        mline = "#define %s(%s) %s" % (macro, arg, mbody)
        block = INLINE_BLOCK.format(pline=pline, mline=mline, arm=arm,
                                    what=what, macro=macro, arg=arg, body=mbody)
        mutant_text = text.replace(inc_line, block.rstrip("\n"))
        mutant = mutant_text.encode("utf-8")

        # measured: exactly one INJECTION MACRO definition differs between the
        # parent header and the mutant source, and the two files are not
        # identical. Counters, not sets: the mutant block re-declares all four
        # macros and then adds the sabotaged one, so the difference is one EXTRA
        # macro line and no missing ones.
        parent_macros = Counter(l for l in hdr_text.split("\n")
                                if l.startswith("#define RAWD_"))
        mutant_macros = Counter(l for l in mutant_text.split("\n")
                                if l.startswith("#define RAWD_"))
        extra = mutant_macros - parent_macros
        missing = parent_macros - mutant_macros
        if mutant == parent:
            raise SystemExit("mutant %s is byte-identical to the parent -- a "
                             "silent no-op" % arm)
        if len(missing) != 0 or sum(extra.values()) != 1:
            raise SystemExit("mutant %s changed %d macro lines (%s missing, %s "
                             "extra), expected exactly one extra"
                             % (arm, sum(missing.values()) + sum(extra.values()),
                                dict(missing), dict(extra)))
        if list(extra.keys())[0] != mline:
            raise SystemExit("mutant %s extra macro line is %r, expected %r"
                             % (arm, list(extra.keys())[0], mline))
        a = text.split("\n")
        b = mutant_text.split("\n")
        only_a = [l for l in a if l not in b]
        only_b = [l for l in b if l not in a]

        d = os.path.join(MUT_DIR, arm)
        os.makedirs(d, exist_ok=True)
        dst = os.path.join(d, "raw_dump_recorder.cpp")
        with open(dst, "wb") as f:
            f.write(mutant)
        out["mutants"][arm] = {
            "arm": arm,
            "what_it_models": what,
            "macro": macro,
            "parent_line": pline,
            "mutant_line": mline,
            "source": os.path.relpath(dst, RAW_DUMP).replace("\\", "/"),
            "sha256": sha(mutant),
            "bytes": len(mutant),
            "differs_from_parent": True,
            "injection_macro_lines_changed": 1,
            "macro_line_extra_in_mutant": list(extra.keys())[0],
            "added_lines_vs_parent": len(only_b),
            "removed_lines_vs_parent": len(only_a),
            "why_the_line_counts_are_not_1": (
                "the mutant inlines the four macro definitions in place of the "
                "single #include line, so the raw added/removed line counts are "
                "not 1; the assertion that matters is that exactly ONE injection "
                "macro definition differs, which is measured above"),
        }
        print("MUTANT %-14s %s" % (arm, mline))
        print("       parent %s" % pline)

    with open(os.path.join(MUT_DIR, "MUTANT_PROVENANCE.json"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(out, indent=1) + "\n")
    print("MUTANTS_EMITTED %d" % len(out["mutants"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
