#!/usr/bin/env python3
"""Phase 16AT RAW_DUMP -- generate the by-value blob length / offset table.

SINGLE SOURCE OF TRUTH
----------------------
p16ao/contracts/FIRST_FRAME_FIELD_CLOSURE.json, fields[] (15 rows).

For each of the 15 identities that are UNRESOLVED, that artefact records:
  * declared_by_value_blob_bytes        -> the exact by-value parameter size
  * declared_by_value_blob_range_bytes  -> [lo, hi) of the blob inside the
                                           KERNARG SEGMENT (hex strings)
  * part_a_static_read_structure
        .what_was_derived.blob_offsets_read -> the byte offsets the kernel's own
                                           ISA body loads, ALSO kernarg-relative

This script does NOT infer anything.  It converts the two kernarg-relative
quantities into the blob-relative coordinates the recorder actually needs
(blob_offset = kernarg_offset - range_lo), asserts the conversion is in range,
and writes:

  p16at/raw_dump/src/raw_dump_blob_table.h   (consumed by the recorder)
  p16at/raw_dump/RAW_DUMP_BLOB_TABLE.json    (human/provenance record)

It records the sha256 and byte length of the source artefact so the table can
be tied back to the exact bytes it came from.

Usage:
  python p16at_emit_blob_table.py            # write
  python p16at_emit_blob_table.py --check    # verify on-disk output matches
"""

import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RAW_DUMP = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(RAW_DUMP))

CLOSURE = os.path.join(ROOT, "p16ao", "contracts",
                       "FIRST_FRAME_FIELD_CLOSURE.json")
OUT_H = os.path.join(HERE, "raw_dump_blob_table.h")
OUT_JSON = os.path.join(RAW_DUMP, "RAW_DUMP_BLOB_TABLE.json")


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def build():
    with open(CLOSURE, "rb") as f:
        raw = f.read()
    closure = json.loads(raw.decode("utf-8"))
    rows = []
    for fld in closure["fields"]:
        if fld.get("resolution_state") != "UNRESOLVED":
            continue
        ident = fld["identity"]
        blen = int(fld["declared_by_value_blob_bytes"])
        lo_s, hi_s = fld["declared_by_value_blob_range_bytes"]
        lo = int(lo_s, 16)
        hi = int(hi_s, 16)
        # The declared size and the declared range must agree; if they ever do
        # not, this generator must fail rather than emit a table that hides it.
        if hi - lo != blen:
            raise SystemExit(
                "RANGE/SIZE DISAGREE for %s: range [0x%x,0x%x) = %d bytes but "
                "declared_by_value_blob_bytes = %d" % (ident, lo, hi, hi - lo, blen))
        kernarg_offsets = [int(x, 16) for x in
                           fld["part_a_static_read_structure"]
                              ["what_was_derived"]["blob_offsets_read"]]
        blob_offsets = []
        for ko in kernarg_offsets:
            bo = ko - lo
            if bo < 0 or bo >= blen:
                raise SystemExit(
                    "READ OFFSET 0x%x OUTSIDE THE BLOB for %s (blob = "
                    "[0x%x,0x%x))" % (ko, ident, lo, hi))
            blob_offsets.append(bo)
        if not blob_offsets:
            raise SystemExit("NO READ OFFSETS for %s -- blob size would be "
                             "unverifiable at run time" % ident)
        rows.append({
            "identity": ident,
            "blob_bytes": blen,
            "kernarg_range_lo": lo,
            "kernarg_range_hi": hi,
            "kernarg_read_offsets": kernarg_offsets,
            "requested_field_offsets": blob_offsets,
        })
    rows.sort(key=lambda r: r["identity"])
    if len(rows) != 15:
        raise SystemExit("expected 15 UNRESOLVED identities, got %d" % len(rows))
    return rows, sha256_file(CLOSURE), os.path.getsize(CLOSURE)


def emit_header(rows):
    L = []
    L.append("// GENERATED by p16at/raw_dump/src/p16at_emit_blob_table.py")
    L.append("// DO NOT EDIT.  Source of truth:")
    L.append("//   p16ao/contracts/FIRST_FRAME_FIELD_CLOSURE.json (fields[])")
    L.append("//")
    L.append("// One row per identity whose scalar_constants field is UNRESOLVED at")
    L.append("// the first-frame contract (520/535).  blob_bytes is that artefact's")
    L.append("// declared by-value parameter size; requested_field_offsets are the")
    L.append("// kernarg-relative read offsets it derived from the identity's own ISA")
    L.append("// body, converted to BLOB-relative by subtracting kernarg_range_lo.")
    L.append("#pragma once")
    L.append("")
    L.append("#include <cstddef>")
    L.append("")
    L.append("namespace raw_dump {")
    L.append("")
    L.append("struct BlobRow {")
    L.append("    const char* identity;")
    L.append("    unsigned blob_bytes;")
    L.append("    unsigned kernarg_range_lo;")
    L.append("    unsigned n_offsets;")
    L.append("    unsigned offsets[16];")
    L.append("};")
    L.append("")
    L.append("inline const BlobRow* blob_table(std::size_t* n)")
    L.append("{")
    L.append("    static const BlobRow t[] = {")
    for r in rows:
        offs = ", ".join("0x%xu" % o for o in r["requested_field_offsets"])
        L.append('        {"%s", %uu, 0x%xu, %uu, {%s}},'
                 % (r["identity"], r["blob_bytes"], r["kernarg_range_lo"],
                    len(r["requested_field_offsets"]), offs))
    L.append("    };")
    L.append("    *n = sizeof(t) / sizeof(t[0]);")
    L.append("    return t;")
    L.append("}")
    L.append("")
    L.append("// Hard cap on a single capture.  The largest blob in the table is %u B;"
             % max(r["blob_bytes"] for r in rows))
    L.append("// the cap exists so that a table entry corrupted into a huge size")
    L.append("// cannot turn the recorder into an unbounded reader.")
    L.append("constexpr unsigned kMaxBlobBytes = 4096u;")
    L.append("")
    L.append("inline const BlobRow* blob_lookup(const char* identity)")
    L.append("{")
    L.append("    if (identity == nullptr) { return nullptr; }")
    L.append("    std::size_t n = 0;")
    L.append("    const BlobRow* t = blob_table(&n);")
    L.append("    for (std::size_t i = 0; i < n; ++i) {")
    L.append("        const char* a = t[i].identity;")
    L.append("        const char* b = identity;")
    L.append("        std::size_t k = 0;")
    L.append("        while (a[k] != '\\0' && a[k] == b[k]) { ++k; }")
    L.append("        if (a[k] == '\\0' && b[k] == '\\0') { return &t[i]; }")
    L.append("    }")
    L.append("    return nullptr;")
    L.append("}")
    L.append("")
    L.append("}  // namespace raw_dump")
    L.append("")
    return "\n".join(L)


def emit_json(rows, src_sha, src_bytes):
    return json.dumps({
        "schema": "p16at/raw-dump-blob-table/1",
        "phase": "16AT",
        "host_only": True,
        "gpu_execution_performed": False,
        "generated_by": "p16at/raw_dump/src/p16at_emit_blob_table.py",
        "source_of_truth": {
            "file": "p16ao/contracts/FIRST_FRAME_FIELD_CLOSURE.json",
            "sha256": src_sha,
            "bytes": src_bytes,
            "selector": "fields[] where resolution_state == UNRESOLVED",
        },
        "what_this_table_is_for": (
            "the recorder must know, at run time, how many bytes of the caller's "
            "by-value parameter image it may read. It does NOT learn that by "
            "guessing: every length here is the by-value size the code object's "
            "own metadata declares, as recorded by 16AO."),
        "what_this_table_is_NOT": (
            "it is not a list of values. It contains no resolved scalar. Every "
            "value in these blobs is still UNRESOLVED; the recorder exists to "
            "capture them at a real launch."),
        "n_rows": len(rows),
        "rows": rows,
    }, indent=1) + "\n"


def main():
    check = "--check" in sys.argv
    rows, src_sha, src_bytes = build()
    header = emit_header(rows)
    doc = emit_json(rows, src_sha, src_bytes)

    if check:
        bad = 0
        for path, want in ((OUT_H, header), (OUT_JSON, doc)):
            if not os.path.exists(path):
                print("MISSING %s" % path)
                bad += 1
                continue
            with open(path, "r", encoding="utf-8", newline="") as f:
                got = f.read()
            if got.replace("\r\n", "\n") != want.replace("\r\n", "\n"):
                print("STALE   %s" % path)
                bad += 1
            else:
                print("OK      %s" % path)
        print("TABLE_CHECK rows=%d bad=%d" % (len(rows), bad))
        return 1 if bad else 0

    with open(OUT_H, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
    with open(OUT_JSON, "w", encoding="utf-8", newline="\n") as f:
        f.write(doc)
    print("WROTE %s (%d bytes)" % (OUT_H, len(header)))
    print("WROTE %s (%d bytes)" % (OUT_JSON, len(doc)))
    print("ROWS  %d" % len(rows))
    for r in rows:
        print("  %-40s blob=%3u lo=0x%02x offsets=%s"
              % (r["identity"], r["blob_bytes"], r["kernarg_range_lo"],
                 ",".join("0x%x" % o for o in r["requested_field_offsets"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
