// GENERATED by p16at/raw_dump/src/p16at_emit_blob_table.py
// DO NOT EDIT.  Source of truth:
//   p16ao/contracts/FIRST_FRAME_FIELD_CLOSURE.json (fields[])
//
// One row per identity whose scalar_constants field is UNRESOLVED at
// the first-frame contract (520/535).  blob_bytes is that artefact's
// declared by-value parameter size; requested_field_offsets are the
// kernarg-relative read offsets it derived from the identity's own ISA
// body, converted to BLOB-relative by subtracting kernarg_range_lo.
#pragma once

#include <cstddef>

namespace raw_dump {

struct BlobRow {
    const char* identity;
    unsigned blob_bytes;
    unsigned kernarg_range_lo;
    unsigned n_offsets;
    unsigned offsets[16];
};

inline const BlobRow* blob_table(std::size_t* n)
{
    static const BlobRow t[] = {
        {"_Z10k_flag_setPjj", 4u, 0x8u, 1u, {0x0u}},
        {"_Z11k_conv_res211Conv2Params", 64u, 0x0u, 2u, {0x0u, 0x20u}},
        {"_Z11k_flag_waitPjjj", 8u, 0x8u, 1u, {0x0u}},
        {"_Z11k_qkv_attn210AttnParams", 40u, 0x0u, 3u, {0x0u, 0x10u, 0x18u}},
        {"_Z12k_attention212AttnParams1d", 40u, 0x0u, 2u, {0x0u, 0x20u}},
        {"_Z12k_final_head10HeadParams", 24u, 0x0u, 2u, {0x0u, 0x10u}},
        {"_Z14k_dec_upsample11DecUpParams", 40u, 0x0u, 2u, {0x0u, 0x20u}},
        {"_Z16k_conv_res_views12ConvPlParams", 72u, 0x0u, 4u, {0x0u, 0x20u, 0x30u, 0x40u}},
        {"_Z6k_mean10MeanParams", 32u, 0x0u, 4u, {0x0u, 0x8u, 0xcu, 0x18u}},
        {"_Z6k_qkv29QkvParams", 40u, 0x0u, 2u, {0x0u, 0x20u}},
        {"_Z7k_ffwd211Ffwd2Params", 48u, 0x0u, 2u, {0x0u, 0x20u}},
        {"_Z8k_export12ExportParams", 64u, 0x0u, 8u, {0x0u, 0x8u, 0xcu, 0x20u, 0x28u, 0x30u, 0x38u, 0x3cu}},
        {"_Z8k_import12ImportParams", 48u, 0x0u, 5u, {0x0u, 0x8u, 0x18u, 0x20u, 0x28u}},
        {"_Z8k_repack12RepackParams", 32u, 0x0u, 4u, {0x0u, 0x10u, 0x14u, 0x1cu}},
        {"_Z9k_expand212ExpandParams", 24u, 0x0u, 2u, {0x0u, 0x10u}},
    };
    *n = sizeof(t) / sizeof(t[0]);
    return t;
}

// Hard cap on a single capture.  The largest blob in the table is 72 B;
// the cap exists so that a table entry corrupted into a huge size
// cannot turn the recorder into an unbounded reader.
constexpr unsigned kMaxBlobBytes = 4096u;

inline const BlobRow* blob_lookup(const char* identity)
{
    if (identity == nullptr) { return nullptr; }
    std::size_t n = 0;
    const BlobRow* t = blob_table(&n);
    for (std::size_t i = 0; i < n; ++i) {
        const char* a = t[i].identity;
        const char* b = identity;
        std::size_t k = 0;
        while (a[k] != '\0' && a[k] == b[k]) { ++k; }
        if (a[k] == '\0' && b[k] == '\0') { return &t[i]; }
    }
    return nullptr;
}

}  // namespace raw_dump
