"""Emit bridge_gfx1030_fatbin.h from a bundle you built yourself.

This is the last step of the bridge payload build DAG
(`src/bridge/bridge_payload_dag.json`, node `embed_header`).

The generated header is NOT published, and this tool being published does not
change that. The header embeds a proprietary code-object payload; the tool
embeds whatever bundle you hand it. Publishing the emitter and withholding
its output is the whole point: a reader can reproduce the header from their
own payload, and the project does not distribute anyone else's.

The header carries the payload and the identity constants that
`registry_ident.cpp` compares, so it is a security-relevant artifact of the
payload, not a copy of it: two different bundles produce two different
headers, and the gate compares the header it was compiled with.

Refuses rather than guesses
---------------------------
Nothing is written unless the bundle parses with the published reader and
carries the requested target. A header emitted from an unparsed or
wrong-target bundle would compile, register, and compare the wrong identity
-- an identity gate that verifies nothing, which is the failure this project
treats as worse than a missing file.

Host-only, stdlib only, read-only on the bundle.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import offload_bundle as ob  # noqa: E402  (path set above)

BYTES_PER_LINE = 16
ARRAY_NAME = "g_gfx1030_fatbin"
SIZE_NAME = "g_gfx1030_fatbin_size"
SHA_NAME = "g_gfx1030_fatbin_sha256"


class EmbedError(Exception):
    """The bundle cannot be embedded, with the reason named."""


def emit(bundle: bytes, target_id: str) -> str:
    """Return the header text for `bundle`.

    Raises `EmbedError` if the bundle does not parse or does not carry
    `target_id`; the caller writes nothing in that case.
    """
    try:
        parsed = ob.parse(bundle, expect_full_span=True)
    except ob.BundleError as exc:
        raise EmbedError(f"the bundle does not parse: {exc}") from exc

    try:
        entry = ob.select_target(parsed, (target_id,))
    except ob.BundleProfileError as exc:
        # Named separately, and the message says which it is. The bundle is
        # well-formed; it is the wrong file. A report that read as corruption
        # would send the reader looking for damage that is not there.
        raise EmbedError(
            f"wrong file, not a corrupt one: {exc}") from exc

    payload = entry.payload(memoryview(bundle))
    digest = hashlib.sha256(bundle).hexdigest()
    payload_digest = hashlib.sha256(payload).hexdigest()

    lines = [
        "// Generated by src/bridge/tools/p11_embed_header.py -- do not edit.",
        "//",
        "// This header is NOT published with this project. It embeds a",
        "// proprietary code-object payload supplied by whoever ran the tool.",
        "// Build it from your own bundle; see docs/bridge-payload-build-dag.md.",
        "//",
        f"// target entry:  {entry.target_id}",
        f"// target offset: {entry.offset:#x}  size: {entry.size:#x}",
        f"// bundle sha256: {digest}",
        f"// payload sha256: {payload_digest}",
        "// Static storage: lifetime == process lifetime, so a substituted",
        "// registration needs no allocation or lifetime management.",
        "#pragma once",
        "#include <stddef.h>",
        "",
        f"static const unsigned char {ARRAY_NAME}[{len(bundle)}] = {{",
    ]
    for i in range(0, len(bundle), BYTES_PER_LINE):
        chunk = bundle[i:i + BYTES_PER_LINE]
        lines.append("    " + ",".join("0x%02x" % b for b in chunk) + ",")
    lines += [
        "};",
        f"static const size_t {SIZE_NAME} = sizeof({ARRAY_NAME});",
        f'static const char {SHA_NAME}[] = "{digest}";',
        "",
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--bundle", required=True,
                    help="a bundle built by tools/p11_bundle_build.py")
    ap.add_argument("--out", required=True,
                    help="header to write, e.g. src/bridge/bridge_gfx1030_fatbin.h")
    ap.add_argument("--target-id", default=ob.GFX1030_TARGET_ID)
    ap.add_argument("--stdout", action="store_true",
                    help="print the header instead of writing it")
    args = ap.parse_args(argv)

    try:
        bundle = open(args.bundle, "rb").read()
        text = emit(bundle, args.target_id)
        if args.stdout:
            sys.stdout.write(text)
            return 0
        with open(args.out, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"bundle: {args.bundle} ({len(bundle)} bytes)")
        print(f"wrote {args.out} ({len(text)} bytes of header)")
        print("STATUS OK")
        return 0
    except (EmbedError, OSError) as exc:
        print(f"STATUS FAILED {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
